### ISSUE TITLE
Update screenshot in appdata

### ISSUE THREAD

**Issue by danrabbit** [tkashkin/Boiler#2]
https://github.com/tkashkin/Boiler/blob/137735cf9dcbf348437f0a1f54f790b10733e8b3/data/com.github.tkashkin.boiler.appdata.xml.in#L38

It looks like names of screenshots have changed :)

**Comment by tkashkin** [comment]
Fixed in 6dea569, [release 0.1.1](https://github.com/tkashkin/Boiler/releases/tag/0.1.1).
